[package]
name = "BuildIT"
version = "0.1.0"
edition = "2024"

[dependencies]
flecs_ecs = "0.1.3"
libloading = "0.8"
common = { path = "common" }

[workspace]
members = [
    "common",
    "plugins/sample-plugin",
]